### ISSUE TITLE
Does not build on Linux

### ISSUE THREAD

**Issue by zeule** [dotnet/ClangSharp#336]
On Gentoo the build fails with:
```
/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lclangAST
/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lclangFrontend
```
Both libraries do not exist in my system.

**Comment by zeule** [comment]
```sh
$ grep add_library /usr/lib/llvm/*/lib64/cmake/clang/ClangTargets.cmake
/usr/lib/llvm/13/lib64/cmake/clang/ClangTargets.cmake:add_library(clang-cpp SHARED IMPORTED)
/usr/lib/llvm/13/lib64/cmake/clang/ClangTargets.cmake:add_library(libclang SHARED IMPORTED)
/usr/lib/llvm/14/lib64/cmake/clang/ClangTargets.cmake:add_library(clang-cpp SHARED IMPORTED)
/usr/lib/llvm/14/lib64/cmake/clang/ClangTargets.cmake:add_library(libclang SHARED IMPORTED)
```

**Comment by zeule** [comment]
Please revert fe454e004737c8330beb5feb20658a197e2f0b3e

**Comment by zeule** [comment]
See #244.

**Comment by tannergooding** [comment]
You'll need to build https://github.com/llvm/llvm-project/tree/llvmorg-14.0.0 locally to get access to the required lib packages given they are not distributed by default in all distros or Operating Systems.

While linking against `clang-cpp` makes it easier for `Gentoo` to build "by default", it makes the experience worse on other platforms and causes the libClangSharp to no longer work by default on most platforms due to `clang-cpp` not being resolvable.

**Comment by zeule** [comment]
> You'll need to build https://github.com/llvm/llvm-project/tree/llvmorg-14.0.0 locally

No, I don't. There was a test in #244, which prefers clang-cpp library, so linking was conditional thus making no problems for other platforms or clang builds with other options enabled. If you want to prefer the other library set, let's invert the test: `if (TARGET clang-ast AND TARGET clang-frontend)` (please check target names in your `ClangTargets.cmake`.

**Comment by tannergooding** [comment]
Dealing with `n+` Linux distributions and the various quirks and oddities that each has in how they package and distribute binaries is out of scope of the project.

Referencing `clang-cpp` was causing many more problems than it was solving and was breaking the user experience for other "officially supported" platforms because the file wasn't resolvable by default.

The simpler thing is to simply require devs to compile `libclang` locally before compiling `libClangSharp` so that all platforms have a consistent experience and expectations. It reduces the overall risk, increases portability, and ensures that we're only relying on dynamic libraries that are available on every platform.

**Comment by zeule** [comment]
I'm afraid you are mistaken about the packaging process for Linux distributions: we strongly prefer dynamic libraries over static ones. I doubt you can find any distro without the  clang-cpp .so library. Neither can I understand the mentioned problems. Referencing the clang-cpp library was under conditional test (if (TARGET clang-cpp)), thus the library has to be available to the linker when the test passes. Could you elaborate on the problems, please?

> …ensures that we're only relying on dynamic libraries that are available on every platform

clangAST and clangFrontend are static libs, clang-cpp is the dynamic one.

**Comment by zeule** [comment]
Ah, so that's what you want! Statically linked binaries! Thank you, now I understand. Then I figure we can replace the test for clang-cpp target with the opposite one for clangAST and clangFrontend and prefer them when they are available. I can submit a PR with the required changes to the CMake build script and I would appreciate if you share with me with the ClangTargets.cmake file from the Windows build of clang with the clangAST & clangFrontend static libraries, please.

**Comment by zeule** [comment]
> if you share with me with theClangTargets.cmake file from the Windows build of clang with the clangAST & clangFrontend static libraries

Pardon, found one online.
