### ISSUE TITLE
is there any solution of serialize ast data and save to file?

### ISSUE THREAD

**Issue by srxqds** [dotnet/ClangSharp#338]
we want to serialize https://github.com/dotnet/ClangSharp/tree/main/sources/ClangSharp/ ast data to file and deserialize it.

**Comment by Perksey** [comment]
No, you'll need to create your own AST file format or use something like CastXML. Note that ClangSharp is able to serialise its generated _bindings_ to XML, but this isn't what you're looking for by the sounds of things.

Hope this helps.

**Comment by tannergooding** [comment]
ClangSharp proper only exposes bindings over libClang plus some external functionality provided by libClangSharp to cover things libClang itself is missing from the Clang C++ API.

ClangSharp P/Invoke Generator only generates XML or C# today.

If the functionality you're looking for is provided by libClang, then ClangSharp supports it. If it's provided by the Clang C++ API, then it might support it or you might need to more explicitly detail what APIs you're needing so I can expose them.

Otherwise, it's likely out of scope.
