### ISSUE TITLE
Problem with stddef.h failed to find on Ubuntu 20.04.5

### ISSUE THREAD

**Issue by DeafMan1983** [dotnet/ClangSharp#414]
Hello, I have big problem with `ClangSharpPInvokeGenerator` because it couldn't find stddef.h from Clang 10 / 11. But I already installed clean Ubuntu 20.04.5.

But I already installed libclangXX-dev
```
locate stddef.h
/opt/rocm-5.4.1/llvm/lib/clang/15.0.0/include/stddef.h
/usr/include/boost/asio/detail/cstddef.hpp
/usr/include/linux/stddef.h
/usr/lib/gcc/x86_64-linux-gnu/7/include/stddef.h
/usr/lib/gcc/x86_64-linux-gnu/9/include/stddef.h
/usr/lib/llvm-10/lib/clang/10.0.0/include/stddef.h
/usr/src/amdgpu-5.18.13-1520974.20.04/include/kcl/kcl_stddef.h
/usr/src/linux-hwe-5.15-headers-5.15.0-56/include/linux/stddef.h
/usr/src/linux-hwe-5.15-headers-5.15.0-56/include/uapi/linux/stddef.h
/usr/src/linux-hwe-5.15-headers-5.15.0-57/include/linux/stddef.h
/usr/src/linux-hwe-5.15-headers-5.15.0-57/include/uapi/linux/stddef.h
/usr/src/linux-hwe-5.15-headers-5.15.0-58/include/linux/stddef.h
/usr/src/linux-hwe-5.15-headers-5.15.0-58/include/uapi/linux/stddef.h
```
I don't understand how do I get successful with `stddef.h`
```
ClangSharpPInvokeGenerator -c multi-file generate-file-scoped-namespaces generate-helper-types --file /usr/include/GLFW/glfw3.h -n Glfw32Intero --libraryPath glfw3 -o Glfw3Interop.cs
Diagnostics for '/usr/include/GLFW/glfw3.h':
    /usr/include/GLFW/glfw3.h:103:10: fatal error: 'stddef.h' file not found
Skipping '/usr/include/GLFW/glfw3.h' due to one or more errors listed above.
```

How do I fix it? Or I need download latest version of clang?

Thanks!

**Comment by tannergooding** [comment]
You often need to explicitly provide the default include directories, as there is not a higher level build system (such as CMake) resolving them automatically.

You can specify these using `--include-directory <path>`

**Comment by GideonUng** [comment]
thats not true. how is this marked as closed? it works on some machines and some it doesnt. i set up 2 ubuntu machines identically and one has the issue and one doesnt.

**Comment by tannergooding** [comment]
> i set up 2 ubuntu machines identically and one has the issue and one doesnt.

If they were setup identically then they would behave identically. Neither ClangSharp nor libClang have any kind of "random" behavior that would cause it to differ in behavior from run to run, so something about your environmental setup differs.

This could include environment variables, terminal environment, startup scripts, tools installed, etc.

Clang by itself doesn't just go searching in arbitrary places, there are a few well known environment variables that can be configured and otherwise it requires everything to be explicitly passed in. The default presumption is that you must pass in all folders you want to be included in the header search paths, unless you've explicitly configured the machine otherwise.

ClangSharp itself is simply deferring down to libClang here, passing in the command line variables given to it. There is no special additional state passed down and so it is the consumers responsibility to ensure that is correct. This is not an issue with ClangSharp or libClang.

**Comment by DeafMan1983** [comment]
Oh sorry for waiting for my response! I think it has missed but for Windows is very lucky but Linux users need to install external packages like libclang/libclangsharp to ClangSharpPInvokeGenerator's directory. Please allow to support for Linux users without required installation of packages. Please embed or bind for required packages for Linux users! I feel jealous if Windows Users dance and don't need to worry about required installing packages ( I caught in ClangSharpPInvokeGenerator's directory with libclang/libclangsharp for Windows only. ) but not for Linux or macOS. It feels arrogantly. Thank you for understanding me!

@GideonUng is right. I feel annoying why does ClangSharpPInvokeGenerator without libclang and libclangsharp libraries for Linux and macOS.

That's why ClangSharpPInvokeGenerator missed to add for detection with correct operating system. Unlike this `<Dependance target="Linux"> ... </Dependance>` or what is about requirements of packages with libclang und libclangsharp. Sorry for my bad English!
