### ISSUE TITLE
Annotating primitive mappings?

### ISSUE THREAD

**Issue by kkukshtel** [dotnet/ClangSharp#428]
Running this against a C library the bool values are mapped to byte. Instead I'd like to use bool with [UnmanagedType.I1] in both extern function params and struct members. Is this possible?

**Comment by tannergooding** [comment]
It would be possible, but it is largely "out of scope" for what ClangSharp is doing today.

The general issue is that `bool` is not considered "blittable" by default and so using something like `[UnmanagedType.I1]` involves marshalling. This represents a hidden cost that can be greatly undesirable for the types of interop bindings.

I plan to eventually add a feature switch that assumes `[assembly: DisableRuntimeMarshallingAttribute]` has been specified and therefore that using `bool` directly for C `bool` is "safe". However, this is a .NET 7+ only feature and it will not involve emitting `[UnmanagedType.I1]`

Adding support for marshalled bindings is an incredibly complex task and is basically impossible to do implicitly due to the wide range of scenarios that even something like `char*` in C could represent. Consider that for starters that the signedness of `char` in C is implementation defined. It could be `signed` or `unsigned`. Then consider that it is the backing type for string literals as well as 8-bit (typically) integers.

So, a `char*` could be:
* a null terminated ascii or utf-8 string
* a byte, sbyte, ascii character, or utf-8 character array
* a pointer to a single byte, sbyte, ascii, or utf-8 character
  * this could itself be `read/write` (equivalent to `ref`) or `write first` (equivalent to `out`)

This requires some mechanism for the consumer of ClangSharp to be able to specify complex annotations per method, field, parameter, etc. There exists some support for doing that today via `--with-attribute` and `--with-type` options alongside the name mapping schemes that are supported, but there isn't a trivial way to provide specifically the specifically the marshalling attributes.

**Comment by kkukshtel** [comment]
Okay gotcha, this makes sense! I also didn't know `DisableRuntimeMarshallingAttribute` would map to a native bool type instead of the Win32 COM mapping, thanks for the info! I agree based on what you said that Marshalled bindings is potentially far out of scope for a lib that just works to generate blittable signatures/types.
