### ISSUE TITLE
Unclear how --traverse is meant to work

### ISSUE THREAD

**Issue by kkukshtel** [dotnet/ClangSharp#432]
I'm working with a header library that relies on a define being set from another library + types provided from that library to work without error. My expectation was that, by passing the dependency in through `--traverse` this would be possible, but it doesn't seem like this is happening.

Concretely, `sokol_gp.h` relies on `sokol_gfx`. sokol_gfx sets SOKOL_GFX_INCLUDED=1, which is required for sokol_gp to not error. Additionally, sokol_gp requires sokol_gfx as it provides types that sokol_gp operates on. Without the traversal of sokol_gfx.h, I'm seeing this:
```md
Diagnostics for './sokol_gp/sokol_gp.h':
    ./sokol_gp/sokol_gp.h:345:2: error: "Please include sokol_gfx.h before sokol_gp.h"
    ./sokol_gp/sokol_gp.h:471:5: error: unknown type name 'sg_image'
    ./sokol_gp/sokol_gp.h:486:5: error: unknown type name 'sg_pipeline'
    ./sokol_gp/sokol_gp.h:500:5: error: unknown type name 'sg_shader_desc'
    ./sokol_gp/sokol_gp.h:501:5: error: unknown type name 'sg_primitive_type'
    ./sokol_gp/sokol_gp.h:515:19: error: unknown type name 'sg_pipeline'
    ./sokol_gp/sokol_gp.h:537:41: error: unknown type name 'sg_pipeline'
    ./sokol_gp/sokol_gp.h:547:51: error: unknown type name 'sg_image'
Skipping './sokol_gp/sokol_gp.h' due to one or more errors listed above.
```

Can you clarify is this is the intended behavior of traverse or if I should be using something else.

For what it's worth, I also tried messing around with a shim header with just:
```c
#include "sokol/sokol_gfx.h"
#include "sokol_gp/sokol_gp.h"
```

and traversed that, but also nothing.

Let me know!

---

Here's the used rsp:
```
--config
latest-codegen
single-file
exclude-funcs-with-body
generate-aggressive-inlining
generate-file-scoped-namespaces
log-exclusions
log-potential-typedef-remappings
log-visited-files
--traverse
./sokol/sokol_gfx.h
--file
./sokol_gp/sokol_gp.h
--namespace
Sokol_CSPGEN
--methodClassName
Sokol
--libraryPath
sokol_gp
--output
./out/clangsharp/sokol_gp.cs
```

**Comment by tannergooding** [comment]
In general `traverse` indicates which visited files (which can be viewed via `log-visited-files`) should actually have bindings generated for them. Other files will generally get visited, but won't have bindings generated and won't walk more than the "top level" declarations.

While I've recently improved how specified `--traverse` paths are matched against the visited files paths, that hasn't been published into a new "stable" version of the tool yet. You should try to use the path specified by `log-visited-files` in the interim.

**Comment by kkukshtel** [comment]
> In general traverse indicates which visited files (which can be viewed via log-visited-files) should actually have bindings generated for them. Other files will generally get visited, but won't have bindings generated and won't walk more than the "top level" declarations.

How is traverse different from --file here? What you're describing is what I thought file did.

Additionally, does the walking persist "state" between files? It seems like files are visited, but that defines set in one file don't apply to the next file visited. If not, this would be exactly what I'm looking for, and ideally implemented as a config option to enable.

**Comment by tannergooding** [comment]
`--file` indicates the individual files that are passed into Clang and for which a syntax tree is generated.

Each of these syntax trees has its top level nodes walked, going into each and every found `#include` until it encounters a node that exists in one of the files specified by `--traverse`. 

Nodes that belong to the files specified by `--traverse` have all the children processed by the binding generator.

-------------------

Consider for example the response file for `vulkan/vulkan_core` here: https://github.com/tannergooding/terrafx.interop.vulkan/blob/main/generation/Vulkan/vulkan/vulkan_core/generate.rsp

We specify `--file vulkan-vulkan_core.h` and `--traverse C:/VulkanSDK/1.3.239.0/Include/vulkan/vulkan_core.h`

The `--file` is https://github.com/tannergooding/terrafx.interop.vulkan/blob/main/generation/Vulkan/vulkan/vulkan_core/vulkan-vulkan_core.h and it has:
```
#include <vulkan/vulkan.h>
#include <vulkan/vulkan_core.h>
```

So Clang is going to parse this file and generate an AST. It is going to start walking it and see that there is `#include <vulkan/vulkan.h>`

It will start walking the nodes of this include and find `#include "vk_platform.h"`, it will start walking the top level nodes of this include and find the `extern "C" {` declaration, it will consider this "top level" and start looking at its nodes, it will then find `#include <stddef.h>` and repeat, all the way through the top level nodes; skipping any non-top level nodes like `structs` or `enums` since they aren't part of the `--traverse` list.

It eventually finishes parsing `vk_platform.h` and all the other includes that are transitively part of that and it gets to `#include "vulkan_core.h"`. Now, all the nodes it walks as part of this will match the entry specified in `--traverse` and so it will actually process things like `structs` and `enums`. It won't, however, include things that are transitively included as part of this. So while `vulkan_core.h` itself has `#include "vk_video/vulkan_video_codec_h264std.h"`, nothing from that file will have bindings generated since that file isn't part of the `--traverse` list.

We have to have the two layer switch due to how C/C++ files must be processed. That is, not everything is allowed to be included directly, many things have one or more dependencies, macros, or other complex setups required before you can include the header. So `--file` allows us to include "anything" and do any pre-include setup required.

Likewise, we cannot just generate bindings for "everything". This is because almost every header indirectly includes things like `Windows.h` or the C/C++ runtime headers. Generating bindings for these would be massively expensive and generally undesirable, so `--traverse` allows us to specify exactly what headers we do actually want bindings from as part of the general AST visitation.

**Comment by kkukshtel** [comment]
Okay I think I understand the difference. I guess for my use case I was missing the difference as I'm running the generator against header-only STB style libs (both STB libs and Sokol). So there was effectively no difference as the file and the traverse were the same.

How does the distinction impact the use of defines for the actual AST? Are defines "set" through --traverse or --file? I'm in a situation where I need a define set at only a certain part in the generation, and not set in others. I thought passing the files in order would solve this but it seems like not.

**Comment by tannergooding** [comment]
Defines work exactly as they would in a regular C/C++ compilation.

If you `#define ...` it exists from that point until a corresponding `#undef` exists. If you you `-D...` then it exists for the entire compilation, likewise until some `#undef` exists.

**Comment by kkukshtel** [comment]
Are the files/traverse parsed in order in a rsp file? I'm imagining I could add in some bunk header file to undef when necessary between file reads if so. How does this interact with setting defines through `-D, --define-macro`?

**Comment by tannergooding** [comment]
> Are the files/traverse parsed in order in a rsp file

They are processed precisely in the order given. It's just a `foreach (var file in files) { }`: https://github.com/dotnet/ClangSharp/blob/main/sources/ClangSharpPInvokeGenerator/Program.cs#L724-L806

All other options passed are shared and so you're often best off calling `ClangSharpPInvokeGenerator` once for each header.

In my own TerraFX.Interop.Windows project I have a `generation/*` folder: https://github.com/terrafx/terrafx.interop.windows/tree/main/generation. This folder contains shared `rsp` files and then a folder per header I want to process containing the per-header options. 

For example, `um/d2d1`: https://github.com/terrafx/terrafx.interop.windows/blob/main/generation/DirectX/um/d2d1/generate.rsp. This includes the general settings response file (`@../../../settings.rsp`), some general typedef remappings (`@../../../remap.rsp`) and then contains the information about the `--file um-d2d1.h` to parse and the specific header within that to traverse `C:/Program Files (x86)/Windows Kits/10/Include/10.0.22621.0/um/d2d1.h`, as well as a few other bits to ensure nicer codegen for stuff that can't be automatically detected due to lack of information in C/C++ (like adding `FlagsAttribute`).

> How does this interact with setting defines through -D, --define-macro?

That'd be the "If you you -D... then it exists for the entire compilation, likewise until some #undef exists." bit I mentioned above. It works exactly as `-D, --define-macro` does with regular C/C++ compilations.

**Comment by kkukshtel** [comment]
Oh okay gotcha! Sorry for blanking out over that line!

This also makes sense I think and maybe is a more idiomatic use of the tool — just running it per header with header specific files instead of trying to generate everything in one pass. I'll give that a go! Thanks for taking the time to clear all this up, hope it helps other people who've got similar questions!

**Comment by kkukshtel** [comment]
For anyone that may run into this again and just for reference, is that the key takeaway is to, if you have complex inter-header deps and defines, the best way to manage this is to just create a shim `.h` file that you point at with `--file`. Then for the defines you want just explicitly specify the target header (not the shim header) as the `--traverse` option.
