### ISSUE TITLE
libclangsharp throws 'due to one or more errors'

### ISSUE THREAD

**Issue by DeafMan1983** [dotnet/ClangSharp#473]
Hello,

I have problem with libclang and libclangsharp and I have tried to resolve under Ubuntu 22.04 with latest ClangSharp version 16.0

But I have copied 2 so files and pasted to ClangSharpPInvokeGenerator's directory then it seems nothing like skipping line.
```
ClangSharpPInvokeGenerator --file ./obs-studio/libobs/obs-source.h -n ObsInterop --methodClassName ObsSource --libraryPath obs -o ./TestObsBindings/ObsInterop.cs --traverse ./obs-studio/libobs/obs-source.h
Error: Parsing failed for './obs-studio/libobs/obs-source.h' due to 'CXError_Failure'.
Skipping './obs-studio/libobs/obs-source.h' due to one or more errors listed above
```

Please fix problem with libclangsharp.so for Ubuntu 22.04.3

**Comment by tannergooding** [comment]
You'll likely have to debug and determine why Clang is complaining. ClangSharp already surfaces all information that Clang reports to it directly, so its potentially some deeper issue with parsing the file.

**Comment by DeafMan1983** [comment]
@tannergooding okay you mean we should use to downgrading clang version? Cause parsing file has bug. I should use ClangSharpPInvokeGenerator 15.x and current version of libclang and libclangsharp. Is it correctly? Thanks for everything!

**Comment by tannergooding** [comment]
I meant that there's not enough information here for me to indicate anything.

Using libClang (and therefore ClangSharp) is a lot like calling `clang` directly from the command line and there is a "lot" of potential stuff that has to be passed along which would normally be handled by the underlying build system (such as `cmake`).

libClang itself then doesn't have very good error messages and so there is only a limited amount of information that ClangSharp can surface back.

You will therefore have to debug things to try and figure out why a given header file can't be parsed. It could be due to a missing macro/define, it could be due to missing includes, it could be something entirely different.

In the worst case, building locally should get you a version of ClangSharp that works for your system and which you can then debug using VS Code, Rider, etc. The instructions for doing that are here: https://github.com/dotnet/ClangSharp?tab=readme-ov-file#building-managed

**Comment by DeafMan1983** [comment]
Thanks for explanation! Now I will close it. I will learn more.. don't worry me!
