### ISSUE TITLE
How to include a system header required by the file to parse

### ISSUE THREAD

**Issue by fredrikhr** [dotnet/ClangSharp#549]
I have a header file that uses types defined in `Windows.h` (e.g. `DWORD`). When I pass my header file into `ClangSharpPInvokeGenerator` it fails with the following error message:

> file.h:1:1: error: unknown type name 'DWORD'

I have tried the following command line options:

- `--include "Windows.h"`
- `--include "<Windows.h>"`
- `--include "#include <Windows.h>"`
- `--traverse "Windows.h"`

none of these did anything useful.

Currently my only other option would be to make a temporary copy of my header file and prepend `#include <Windows.h>` to it, but that seems like a very sad solution. I am sure there is a better way, but the solution eludes me.

**Comment by tannergooding** [comment]
> Currently my only other option would be to make a temporary copy of my header file and prepend #include <Windows.h> to it, but that seems like a very sad solution. I am sure there is a better way, but the solution eludes me.

This is exactly what you have to do.

All `ClangSharp` is doing is passing the header files, as is, down to `libClang` to get back the AST. This necessitates that the header files processed are themselves valid C/C++ headers, such that they can be parsed, have types resolved, etc.

-------------------------

As an aside, it is generally considered "best practice" to have your header file include dependencies so that users aren't having to do it themselves. There are many different style guides across the internet and they all essentially recommend the same thing. One such example is the style guide that Google uses themselves: https://google.github.io/styleguide/cppguide.html#Self_contained_Headers
